### PR TITLE
Include version compatibility check

### PR DESCRIPTION
**Pull request by dtomvan**
Will test this later in the day.

### CODE REVIEW

**Review by sayanarijit — DISMISSED** [review]
Nice...

**Comment by dtomvan** [comment]
@sayanarijit is there maybe an API call which sends messages, or even better, an error (invalid config screen)?

**Comment by sayanarijit** [comment]
I think simple `assert` should work fine. xplr will display the error raised by Lua by default.

**Review by dtomvan — COMMENTED** [review]
Checked and tested. Does block anything under xplr v0.20.0.

**Pull request merged**
